### ISSUE TITLE
Can Early stopping be graceful ..not throw exception ?

### ISSUE THREAD

**Issue by rcherukuri12** [jondeuce/Ignite.jl#3]
Hi Jon,
Early termination is normal part of daily training. 
Is there a way you can make it without Exception being triggered ?

Something like updating the max_epochs of the run method to end the training.

**Comment by jondeuce** [comment]
Yeah this is probably a good idea. I was thinking about this while addressing your previous issue. Perhaps I should differentiate between terminating a run (via `Ignite.terminate!`), which indicates a failure of some kind, and finishing a run early (e.g. via a new method `Ignite.finish!`), which would gracefully exit without error messages etc.

Similarly, one may be interesting in restarting an interrupted run. But this may be a bit trickier.

**Comment by jondeuce** [comment]
Would something like a delayed termination work? Maybe `Ignite.finish!` won't throw an error, but will stop training after the current iteration is finished (including any event handlers)?

**Comment by rcherukuri12** [comment]
That would be perfect. Thank you

**Comment by jondeuce** [comment]
Alright, after some thought I've decided to go with your original suggestion. As it turns out, this is what PyTorch Ignite does, and I think it's the right idea.

See the [updated docs](https://github.com/jondeuce/Ignite.jl#terminating-a-run) for details, but basically `Ignite.terminate!(engine)` will now terminate gracefully after the current iteration has finished without throwing an exception. If you want to terminate a run immediately for some reason without firing any other events (`NaN` weights, etc.), just throw an error as usual.

This is technically a breaking change, so update to v0.2.0 for the new functionality :+1:
